### ISSUE TITLE
API of msgRecv() and msgRespond() changed.

### ISSUE THREAD

**Issue by gerard5** [phoenix-rtos/libphoenix#70]
The following commit
https://github.com/phoenix-rtos/libphoenix/commit/a1b4d5eeec94dc7b6a146ac7bda7f49cdc0e2de6#diff-b8ddf54fbb3816a9bcebb40723b6b2dc
introduced changes to `msgRecv` and `msgRespond` functions and the only use case of this change is
https://github.com/phoenix-rtos/phoenix-rtos-devices/commit/33d10f81cab8a4686f4c8def0385b9cb1cb97411#diff-ee960f11796384fd0e55db06d178002eR267
the other device drivers (and repositories used internally) have not been updated accordingly to the change a1b4d5eeec94dc7b6a146ac7bda7f49cdc0e2de6 and still use `unsigned int` instead of `unsigned long int` for the `rid` parameter. Due to the unification of the repositories used internally with the changes introduced recently in the `libphoenix`, I'm asking for the guidance on the proper usage of the API whether `unsigned int` is to be replaced by `unsigned long int` in other repos too (warnings treated as errors)?

**Comment by nalajcie** [comment]
Personally I don't know why the `unsigned int` was changed to `unsigned long int` - was it to maintain the same byte width for 32- and 64-bit architectures? If so, fixed-len type should have been used (eg. `uint64_t`).

As this part of RISC-V work done by @youki0 was merged while being still in progress, I don't know if this change was really needed.

@pawelpisarczyk, @agkaminski what should be done?
* should we revert to `unsigned int`
* should we use `unsigned long int` and update all drivers
* should we switch to fixed-width type and update all drivers

**Comment by agkaminski** [comment]
As for now we can change it everywhere to unsigned long.

**Comment by pawelpisarczyk** [comment]
Guys, let me comment. I've changed 'unsigned int' to 'unsigned long' because of problems discovered on 64-bit architectures. The aim of the rid is to represent the handle to received message. The handle is required to confirm that message is completely handled by the receiver and  to wake-up the sending thread. Unfortunately, rid represents the address of kmsg_t structure in the kernel space (I know that this is ugly hack, it is vulnerable and should be changed). The unsigned int type is insufficient  on 64-bit architectures, so I decided to change this to 'unsigned long' which has the same size as pointer. This is temporary solution, but please change unsigned int to unsigned long when you use rid.

**Comment by gerard5** [comment]
Closing, I do not find any more occurrences of the issue in the repositories available to me.
